numbers = input("Enter numbers separated by commas: ")
num_list = numbers.split(",")
num_tuple = tuple(num_list)
print("List: ", num_list)
print("tuple: ", num_tuple)
name = input("enter your name separated by commas: ")
name_list = name.split(",")
name_tuple = tuple(name_list)
print("List: ", name_list)
print("Tuple: ", name_tuple)